all: build_server build_server_poll build_server_epoll

build_server:
	g++ -std=c++11 -o server server.cpp

build_server_poll:
	g++ -std=c++11 -o server_poll server_poll.cpp

build_server_epoll:
	g++ -std=c++11 -o server_epoll server_epoll.cpp